services:
  # the actual db
  stats-mongo:
    image: mongo
    container_name: stats-mongodb-container
    restart: always
    volumes:
      - ./import:/docker-entrypoint-initdb.d:ro
    networks:
      - stats-internal-net

  # the management interface to the db 
  stats-mongo-express:
    depends_on:
      - stats-mongo
    image: mongo-express
    restart: always
    ports:
      # for development purposes only
      - ${STATS_DB_UI_PORT:-8081}:8081
    networks:
      - stats-internal-net 
    environment:
      ME_CONFIG_MONGODB_SERVER: stats-mongodb-container
      # TODO: use auth to access this or remove entirely on deploy
      ME_CONFIG_BASICAUTH: false

  # the api built on top of the db
  stats-frontend:
    build: .
    container_name: stats-api
    depends_on:
      - stats-mongo
    ports:
      - ${STATS_API_PORT}:${STATS_API_PORT}
    networks:
      - stats-internal-net
      - town-of-saviom-shared-net
    environment:
      # mongodb-container -> nome container del db
      # stats -> nome del db
      - MONGO_URI=mongodb://stats-mongodb-container:27017/stats
      # production or debug
      - NODE_ENV=debug
      # auth-service container url
      - AUTH_SERVICE_URL=#{AUTH_SERVICE_URL}
      # origin url accepted by cors
      - CORS_ORIGIN=http://localhost:517

networks:
  stats-internal-net:
    driver: bridge
  town-of-saviom-shared-net:
    external: true